import { Inter } from "next/font/google";
import "/styles/globals.css";
import Headers from "@/components/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body className='bg-orange-300 h-screen w-screen min-h-screen flex font-sans'>
            	<Headers/>
				<div className="mt-20 flex-grow overflow-auto">
              		{children}
				</div>
            </body>
        </html>
    );
}
